import Head from 'next/head'
import { useSession } from 'next-auth/react'
import Image from 'next/image'
import Link from 'next/link'

const UserDashboard = () => {
  const { data } = useSession()

  return (
    <>
      <Head>
        <title>Welcome to EnsoCircle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="relative grid h-screen mt-20 lg:mt-0 lg:place-items-center bg-gray-50">
          <div className="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8">
            <div className="grid items-center max-w-4xl grid-cols-1 mx-auto lg:grid-cols-2 gap-x-16 gap-y-12">
              <div>
                <div className="max-w-lg mx-auto text-center lg:text-left lg:max-w-none lg:mx-0">
                  <h2 className="text-sm font-bold tracking-wide uppercase text-rose-500">
                    WELCOME
                  </h2>
                  <p className="mt-4 text-5xl font-bold text-gray-900 md:text-6xl">
                    Hi {data?.user?.name || 'User'}
                  </p>
                  <p className="mt-6 text-lg font-medium text-gray-600">
                    Welcome to Dashboards.
                  </p>
                  <p className="text-lg mt-2 font-medium text-gray-600">
                    We are super excited to have you onboard!
                  </p>
                  <p className="text-lg font-medium text-gray-600">
                    Let&apos;s set up your account and boost your online
                    experiences.
                  </p>
                </div>

                <div className="flex items-start max-w-xs mx-auto mt-10 lg:mt-25 lg:max-w-none lg:mx-0 gap-x-16">
                  <div>
                    <p className="text-base font-medium text-gray-500">
                      Member Plan
                    </p>
                    <p className="mt-2 text-3xl font-bold text-gray-900">
                      Ξ Pro
                    </p>
                  </div>

                  <div>
                    <p className="text-base font-medium text-gray-500">
                      Monthly Credits Available
                    </p>
                    <p className="mt-2 text-3xl font-bold text-gray-900">
                      1000
                    </p>
                  </div>
                </div>
              </div>

              <div>
                <div className="max-w-xs mx-auto overflow-hidden bg-white border border-gray-100 rounded-lg shadow-xl shadow-gray-500/10">
                  <div className="p-4">
                    <div className="mt-4 overflow-hidden rounded-lg aspect-w-1 aspect-h-1">
                      <Image
                        className="object-cover w-full h-full"
                        src="https://landingfoliocom.imgix.net/store/collection/niftyui/images/featured-drops-single/4/drop-1.png"
                        alt=""
                        height={300}
                        width={200}
                      />
                    </div>

                    <div className="flex items-center justify-between mt-4 space-x-6">
                      <p className="flex-1 text-base font-bold text-gray-900">
                        Pro User:
                        <br />
                        {data?.user?.name || 'User'}
                      </p>

                      <div className="text-right shrink-0">
                        <p className="text-sm font-medium text-gray-500">
                          Credits Available
                        </p>
                        <p className="mt-0.5 text-lg font-bold text-emerald-500">
                          1000 / 1000
                        </p>
                      </div>
                    </div>

                    <div className="flex items-center justify-between mt-4 space-x-4">
                      <Link
                        href="/dashboard"
                        className="inline-flex items-center justify-center w-full px-4 py-3 text-xs font-bold tracking-widest text-gray-900 text-center uppercase transition-all duration-200 bg-transparent border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900 hover:border-gray-900 hover:bg-gray-900 hover:text-white"
                      >
                        Edit Profile
                      </Link>

                      <Link
                        type="button"
                        href="/dashboard"
                        className="inline-flex items-center justify-center w-full px-4 py-3 text-xs font-bold tracking-widest text-white text-center uppercase transition-all duration-200 bg-gray-900 border border-transparent rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-900 hover:bg-gray-700"
                      >
                        Go to Dashboard
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  )
}

export default UserDashboard
