import { useEffect } from 'react'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import UserNavBar from './UserNavbar'
import UserSidebar from './UserSidebar'
import type { ReactNode } from 'react'

const UserLayout = ({
  children,
  title
}: {
  children: ReactNode
  title: string
}) => {
  const router = useRouter()
  const { status } = useSession()
  useEffect(() => {
    if (status === 'unauthenticated') {
      void router.push('/signin')
    }
  }, [router, status])

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="robots" content="noindex,nofollow" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <UserNavBar />
        <div className="flex flex-1">
          <UserSidebar />
          <main className="bg-gray-100 w-full">
            <section className="relative w-full h-full min-h-screen">
              {children}
            </section>
          </main>
        </div>
      </div>
    </>
  )
}

export default UserLayout
